[general]
import = [
  "~/.config/alacritty/rose-pine-moon.toml"
]
live_config_reload = true

[window]
padding = { x = 40, y = 40 }
opacity = 1.0
blur = true

[scrolling]
history = 0 
multiplier = 1

[font]
normal = { family = "BlexMono Nerd Font", style = "Smbld" }
bold = { family = "BlexMono Nerd Font", style = "Bold" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Italic Smdld" }
size = 18.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
