[general]
import = [
  "~/.config/alacritty/rose-pine-dawn.toml"
]
live_config_reload = true

[window]
padding = { x = 40, y = 40 }
opacity = 1.0
blur = true

[scrolling]
history = 0 
multiplier = 1

[font]
#normal = { family = "IBM Plex Mono" }
#bold = { family = "IBM Plex Mono", style = "Smdld" }
#italic = { family = "IBM Plex Mono", style = "Italic" }
#bold_italic = { family = "IBM Plex Mono", style = "Italic Smdld" }
size = 18.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
