[general]
import = [
  # "~/.config/alacritty/rose-pine-moon.toml"
  "~/.config/alacritty/colorthemes/material_colors.toml"
]
live_config_reload = true

[window]
padding = { x = 30, y = 30 }
opacity = 1.0
blur = true

[scrolling]
history = 100
multiplier = 1

[font]
normal = { family = "BlexMono Nerd Font", style = "Smbld" }
bold = { family = "BlexMono Nerd Font", style = "Bold" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Italic Smdld" }
size = 15.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
