[colors]
cursor = { text = "CellForeground", cursor = "#cecacd" }
selection = { text = "#575279", background = "#dfdad9" }

[colors.hints]
start = { foreground = "#c4a7e7", background = "CellBackground" }
end = { foreground = "#c4a7e7", background = "CellBackground" }

[colors.primary]
foreground = "#575279"
background = "#191817"

[colors.bright]
black = "#9893a5"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"

[colors.normal]
black = "#f2e9e1"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
